on: [pull_request]
name: Performance
jobs:
  runBenchmark:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run benchmark
        uses: matchai/criterion-compare-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
